# Generated by Django 5.2.17 on 2026-08-17 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reportrun',
            constraint=models.UniqueConstraint(fields=('account', 'date_start', 'date_end'), name='uniq_report_account_period'),
        ),
    ]
