# Generated by Django 5.2.17 on 2026-08-18 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_reportrun_uniq_report_account_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reportrun',
            name='uniq_report_account_period',
        ),
        migrations.AddField(
            model_name='reportrun',
            name='included_accounts',
            field=models.ManyToManyField(blank=True, related_name='portfolio_reports', to='reporting.adaccount'),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='scope',
            field=models.CharField(choices=[('account', 'Compte Meta'), ('portfolio', 'Tous les comptes Meta')], default='account', max_length=16),
        ),
        migrations.AlterField(
            model_name='reportrun',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reporting.adaccount'),
        ),
        migrations.AddIndex(
            model_name='reportrun',
            index=models.Index(fields=['scope', '-date_end'], name='reporting_r_scope_0e1498_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportrun',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'account')), fields=('account', 'date_start', 'date_end'), name='uniq_report_account_period'),
        ),
        migrations.AddConstraint(
            model_name='reportrun',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'portfolio')), fields=('date_start', 'date_end'), name='uniq_report_portfolio_period'),
        ),
    ]
